query MyQuery {
                countries {
                  name
                  phone
                  code
                  currency
                  emoji
                  languages {
                    name
                  }
                  states {
                    name
                  }
                  capital
                }
                
}

