# query MyQuery{
#     countrie(code : $variable){
#                   name
#                   phone
#                   code
#                   currency
#                   emoji
#                   languages {
#                     name
#                   }
#                   states {
#                     name
#                   }
#                   capital
#                 }
#     }
# }